# Generated by Django 4.1 on 2024-09-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_delete_tasks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="complated",
        ),
        migrations.AddField(
            model_name="task",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
